name: Griewank
n_tot: 20
N_init: 10
delta: 0.5
dim: 5
M: 3
lb: -300
ub: 300
params:
  random: true

fn:
  _target_: botorch.test_functions.synthetic.Griewank
  dim: ${..dim}
  negate: False  # Negate the function to turn it into a minimization problem
  noise_std: 0.0  # Stdv of Gaussian noise to add to observations (to test optimization under noise)
