name: Griewank
n_tot: 20
N_init: 10
delta: 0.5
dim: 5
M: 3
lb: -300
ub: 300
params:
  random: true
  center: False
  init: null

fn:
  _target_: botorch.test_functions.synthetic.Griewank
  dim: ${..dim}
  negate: False  # Negate the function to turn it into a minimization problem
