name: Pusher
n_tot: 300
N_init: 100
N_max: 280
delta: 0.2
dim: 14
M: 14
target_dim_init: 1
lb: [-5.0, -5.0, -10.0, -10.0, 2.0, 0.0, -5.0, -5.0, -10.0, -10.0, 2.0, 0.0, -5.0, -5.0]
ub: [5.0, 5.0, 10.0, 10.0, 30.0, 6.283185307179586, 5.0, 5.0, 10.0, 10.0, 30.0, 6.283185307179586, 5.0, 5.0]
start_point: center  # random | center | init | best_sobol
init_point: null  # starting point in [lb, ub], used when start_point=init

fn:
  _target_: src.benchmark.push_function.Push_RL

