name: Rover
n_tot: 800
N_init: 10
delta: 0.2
dim: 60
M: 60
target_dim_init: 30
lb: -0.1
ub: 1.1
params:
  random: False
  center: true
  init: null

fn:
  _target_: src.benchmark.rover_function.rover_fun

