name: Sphere
n_tot: 500
N_init: 10
delta: 0.2
dim: 20
M: 20
lb: -400
ub: 400
params:
  random: true
  center: False
  init: null

fn:
  _target_: src.benchmark.Sphere.Sphere
  dim: ${..dim}
  negate: False  # Negate the function to turn it into a minimization problem
