name: Sphere
n_tot: 500
N_init: 10
delta: 0.2
dim: 20
M: 20
lb: -400
ub: 400
start_point: random  # random | center | init | best_sobol
init_point: null  # starting point in [lb, ub], used when start_point=init

fn:
  _target_: src.benchmark.Sphere.Sphere
  dim: ${..dim}
  negate: False  # Negate the function to turn it into a minimization problem
